version: '3.8'

services:
  ssh-server:
    image: linuxserver/openssh-server
    container_name: ssh_lab
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Ljubljana
      - PASSWORD_ACCESS=true
      - USER_NAME=student
      - USER_PASSWORD=password123
    ports:
      - "2222:2222"
    volumes:
      - ./config:/config
      - ./create_users.sh:/create_users.sh
    restart: unless-stopped
